### ISSUE TITLE
Setup - RPP not found with rocm 5.4

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#985] opened 2022-10-21 17:36 UTC
@kiritigowda A couple of issues with ubuntu22 & rocm5.4:

- [ ] While building FFMPEG, it says 
```
ERROR: libass not found using pkg-config
```
Solution: 
```
apt install libass-dev
```
Please add this to MIVisionX-setup script

- [ ] RPP not found even though it builds correctly
```
cmake ..
-- MIVisionX Version -- 2.4.0
-- MIVisionX Install Path -- /opt/rocm-5.4.0-10980
-- MIVisionX Backend set to -- HIP
-- MIVisionX Build Type -- Release
-- MIVisionX Developer Options
--      -D NEURAL_NET=ON [Turn ON/OFF Neural Net Modules (default:ON)]
--      -D ROCAL=ON [Turn ON/OFF ROCAL Modules (default:ON)]
--      -D LOOM=ON [Turn ON/OFF LOOM Modules (default:ON)]
--      -D GPU_SUPPORT=ON [Turn ON/OFF GPU support (default:ON)]
--      -D MIGRAPHX=ON [Turn ON/OFF MIGraphX Module (default:ON)]
--      -D BACKEND=HIP [Select MIVisionX Backend [options:CPU/OPENCL/HIP](default:HIP)]
--      -D AMD_FP16_SUPPORT=OFF [Turn ON/OFF OpenVX FP16 Support (default:OFF)]
-- hip::amdhip64 is SHARED_LIBRARY
-- AMD OpenVX -- Using HIP -- Path:/opt/rocm-5.4.0-10980        Version:5.4.22401       Compiler:clang
-- AMD OpenVX -- OpenVX built with HIP Support
-- AMD OpenVX -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -msse4.2 -std=gnu++14
-- AMD OpenVX -- OpenVX module added
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- amd_media -- Building with HIP
-- amd_media -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -Wno-deprecated-declarations -msse4.2 -std=gnu++14
-- AMD OpenVX Media Extension -- amd_media module added
-- hip::amdhip64 is SHARED_LIBRARY
-- vx_amd_custom -- Building with HIP backend
-- hip::amdhip64 is SHARED_LIBRARY
-- custom_lib -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -fopenmp -fPIC -std=gnu++14
-- AMD Custom Extension -- amd_custom module added
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- amd_nn -- Building with HIP
-- amd_nn -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -msse4.2 -std=gnu++14
-- AMD OpenVX Neural Network Extension -- amd_nn module added with HIP backend
-- WARNING: /opt/rocm-5.4.0-10980/include/rpp/rpp_backend.h file Not Found. please run the setup script to install latest RPP package 
-- WARNING: RPP with the HIP backend Not Found (HINT: run setup script with the HIP backend first!) -- amd_rpp module excluded.
-- OpenCV Found -- Version-4.5.X
-- OpenCV Version Supported -- Version-4.5.X
-- vx_opencv -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -fdata-sections -std=gnu++14
-- AMD OpenVX OpenCV Extension -- amd_opencv module added
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- vx_amd_migraphx -- Building with HIP backend
-- vx_migraphx -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -msse4.2 -std=gnu++14
-- AMD OpenVX MIGraphX Extension -- amd_migraphx module added with the HIP backend
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- runVX -- Using HIP -- Path:/opt/rocm-5.4.0-10980     Version:5.4.22401       Compiler:clang
-- runvx built with HIP Support
-- runVX -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -DHAVE_OpenSSL=1 -std=gnu++14
-- Utilities -- runvx and mv_deploy modules added
-- hip::amdhip64 is SHARED_LIBRARY
-- rocAL -- Using HIP -- Path:/opt/rocm-5.4.0-10980     Version:5.4.22401       Compiler:clang
-- WARNING: /opt/rocm-5.4.0-10980/include/rpp/rpp_backend.h file Not Found. please run the setup script to install latest RPP package 
-- WARNING: RPP with the HIP backend Not Found (HINT: run setup script with the HIP backend first!) -- rocAL_rpp module excluded.
-- WARNING: rocAL module excluded 
-- Configuring done
-- Generating done
-- Build files have been written to: /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/lakshmi/MIVisionX/build
root@Legolas:~/lakshmi/MIVisionX/build# rm -rf *
root@Legolas:~/lakshmi/MIVisionX/build# cmake ..
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/.sccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/.sccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- MIVisionX Version -- 2.4.0
-- MIVisionX Install Path -- /opt/rocm
-- MIVisionX Backend set to -- HIP
-- MIVisionX Build Type -- Release
-- MIVisionX Developer Options
--      -D NEURAL_NET=ON [Turn ON/OFF Neural Net Modules (default:ON)]
--      -D ROCAL=ON [Turn ON/OFF ROCAL Modules (default:ON)]
--      -D LOOM=ON [Turn ON/OFF LOOM Modules (default:ON)]
--      -D GPU_SUPPORT=ON [Turn ON/OFF GPU support (default:ON)]
--      -D MIGRAPHX=ON [Turn ON/OFF MIGraphX Module (default:ON)]
--      -D BACKEND=HIP [Select MIVisionX Backend [options:CPU/OPENCL/HIP](default:HIP)]
--      -D AMD_FP16_SUPPORT=OFF [Turn ON/OFF OpenVX FP16 Support (default:OFF)]
-- hip::amdhip64 is SHARED_LIBRARY
-- AMD OpenVX -- Using HIP -- Path:/opt/rocm-5.4.0-10980        Version:5.4.22401       Compiler:clang
-- AMD OpenVX -- OpenVX built with HIP Support
-- AMD OpenVX -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -msse4.2 -std=gnu++14
-- AMD OpenVX -- OpenVX module added
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.134.100
-- Checking for module 'libavformat'
--   Found libavformat, version 58.76.100
-- Checking for module 'libavutil'
--   Found libavutil, version 56.70.100
-- Using FFMPEG -- 
        Libraries:/usr/local/lib/libavcodec.so;/usr/local/lib/libavformat.so;/usr/local/lib/libavutil.so;/usr/local/lib/libswscale.so 
        Includes:/usr/local/include
-- Found Threads: TRUE  
-- hip::amdhip64 is SHARED_LIBRARY
-- amd_media -- Building with HIP
-- amd_media -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -Wno-deprecated-declarations -msse4.2 -std=gnu++14
-- AMD OpenVX Media Extension -- amd_media module added
-- hip::amdhip64 is SHARED_LIBRARY
-- vx_amd_custom -- Building with HIP backend
-- hip::amdhip64 is SHARED_LIBRARY
-- custom_lib -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -fopenmp -fPIC -std=gnu++14
-- AMD Custom Extension -- amd_custom module added
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- amd_nn -- Building with HIP
-- amd_nn -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -msse4.2 -std=gnu++14
-- AMD OpenVX Neural Network Extension -- amd_nn module added with HIP backend
-- WARNING: /opt/rocm-5.4.0-10980/include/rpp/rpp_backend.h file Not Found. please run the setup script to install latest RPP package 
-- WARNING: RPP with the HIP backend Not Found (HINT: run setup script with the HIP backend first!) -- amd_rpp module excluded.
-- OpenCV Found -- Version-4.5.X
-- OpenCV Version Supported -- Version-4.5.X
-- vx_opencv -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -fdata-sections -std=gnu++14
-- AMD OpenVX OpenCV Extension -- amd_opencv module added
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- vx_amd_migraphx -- Building with HIP backend
-- vx_migraphx -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -msse4.2 -std=gnu++14
-- AMD OpenVX MIGraphX Extension -- amd_migraphx module added with the HIP backend
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- runVX -- Using HIP -- Path:/opt/rocm-5.4.0-10980     Version:5.4.22401       Compiler:clang
-- runvx built with HIP Support
-- runVX -- CMAKE_CXX_FLAGS: -O3 -DNDEBUG -fPIC -DHAVE_OpenSSL=1 -std=gnu++14
-- Utilities -- runvx and mv_deploy modules added
-- hip::amdhip64 is SHARED_LIBRARY
-- rocAL -- Using HIP -- Path:/opt/rocm-5.4.0-10980     Version:5.4.22401       Compiler:clang
-- WARNING: /opt/rocm-5.4.0-10980/include/rpp/rpp_backend.h file Not Found. please run the setup script to install latest RPP package 
-- WARNING: RPP with the HIP backend Not Found (HINT: run setup script with the HIP backend first!) -- rocAL_rpp module excluded.
-- WARNING: rocAL module excluded 
-- Configuring done
-- Generating done
-- Build files have been written to: /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/lakshmi/MIVisionX/build
```

**Comment by kiritigowda** [comment] 2022-11-03 21:32
Duplicate of #969

**Closed by kiritigowda** 2022-11-03 21:32 UTC
Labels: bug
